### ISSUE TITLE
How to use the fingerprint feature extracted

### ISSUE THREAD

**Issue by Mentor-Roma** [Utkarsh-Deshmukh/Fingerprint-Feature-Extraction#10]
How to view and use the minutiae informations extracted using the extractor library?
Hint code from the author...

    for current_feature_termination in FeaturesTerminations:
        print(str(current_feature_termination.locX) + ' ' + str(current_feature_termination.locY), ' ' + str(current_feature_termination.Orientation) , ' ' + str(current_feature_termination.Type))

    for current_feature_termination in FeaturesBifurcations:
        print(str(current_feature_termination.locX) + ' ' + str(current_feature_termination.locY), ' ' + str(current_feature_termination.Orientation) , ' ' + str(current_feature_termination.Type))
#==============================================================================================================

the variables "FeaturesTerminations" and "FeaturesBifurcations" are arrays of a class "MinutiaeFeature". The class is defined as:
class MinutiaeFeature(object):
    def __init__(self, locX, locY, Orientation, Type):
        self.locX = locX;
        self.locY = locY;
        self.Orientation = Orientation;
        self.Type = Type;

you can get the total number of minutiae by doing: len(FeaturesTerminations)

*Works very well*

**Comment by Utkarsh-Deshmukh** [comment]
Thank you for raising this topic.
Just rephrasing the above answer:
the resultant minutaie features are stored as a array of the class `MinutiaeFeature`.
The definition of this class looks like this:

```
class MinutiaeFeature(object):
    def __init__(self, locX, locY, Orientation, Type):
        self.locX = locX
        self.locY = locY
        self.Orientation = Orientation
        self.Type = Type
```

each element in this result array can be accessed as `result_array[i].locX`, `result_array[i].locY`, `result_array[i].Orientation`, `result_array[i].Type`
