### ISSUE TITLE
The number of fingerprint feature points drawn by opencv is not the same as the number of feature points extracted

### ISSUE THREAD

**Issue by hipforth** [Utkarsh-Deshmukh/Fingerprint-Feature-Extraction#11]
Thanks for your work!

in function 'def showResults'
I get opecv show 16 Term feature, as follow:
![image](https://user-images.githubusercontent.com/39158521/153905551-b3b5c8e1-9a4b-40d3-8319-24a45e3fce83.png)
and the result  len(FeaturesTerm) is 14, as follow:
![image](https://user-images.githubusercontent.com/39158521/153905810-75cbdefd-9dd0-4959-a128-9a69bc3d8fb6.png)
what happened？

**Comment by Utkarsh-Deshmukh** [comment]
can you send me the original image that generated this?

**Comment by hipforth** [comment]
> can you send me the original image that generated this?
[test_rotaed.zip](https://github.com/Utkarsh-Deshmukh/Fingerprint-Feature-Extraction/files/8069377/test_rotaed.zip)

and I found that it was missing one of the four Term in the center.

**Comment by Utkarsh-Deshmukh** [comment]
this is happening because the display function is buggy. I will push a fix for this soon. Thank you for pointing it out.

**Comment by Utkarsh-Deshmukh** [comment]
the bug is fixed now.
