### ISSUE TITLE
Can't install!

### ISSUE THREAD

**Issue by ndaniel99** [Utkarsh-Deshmukh/Fingerprint-Feature-Extraction#13]
I can't get over this installing error:

Collecting fingerprint-feature-extractor
  Using cached fingerprint-feature-extractor-0.0.8.tar.gz (4.2 kB)
  Preparing metadata (setup.py) ... done
Collecting numpy==1.19.0
  Using cached numpy-1.19.0.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

Can anyone help me?

I already make sure pip setuptools and wheels are updated.

OS: MacOS

**Comment by Utkarsh-Deshmukh** [comment]
sorry for the late reply. I have pushed a new patch. hopefully it works. Can you please check it and verify it for me?

**Comment by Utkarsh-Deshmukh** [comment]
closing this issue. please feel free to reopen this if the issue persists.
