### ISSUE TITLE
How is orientation represented?

### ISSUE THREAD

**Issue by kshitij86** [Utkarsh-Deshmukh/Fingerprint-Feature-Extraction#14]
The extractor give the following output for orientation, what is the meaning of these values and how can the angle be computed using these values, if I wanted to apply say Generalized Hough Transform?

```
[135.0, -0.0, -90.0]
```

**Comment by Utkarsh-Deshmukh** [comment]
this must be for a ridge bifurcation. when we encounter ridge bifurcation, one ridge is split into two. Hence we have the three angles. compare this with ridge terminations, in which the ridge is going only in one direction, and hence has only one angle.

Note: angles computed are in degrees. hence, in your example, at the ridge bifurcation point, the three ridges are travelling in the orientation of 135, 0, and 90 degrees respectively.

Hope this answers the question.
