### ISSUE TITLE
minutiae points extraction

### ISSUE THREAD

**Issue by nguThapelo** [Utkarsh-Deshmukh/Fingerprint-Feature-Extraction#15]
I want to display the minutiae coordinates in a tubular form, the x, y, orientation and type. I am not sure how to extract the coordinates from the fingerprint_feature_extractor function

**Comment by Utkarsh-Deshmukh** [comment]
when you extract the minutiae feature using the command:
`FeaturesTerminations, FeaturesBifurcations = fingerprint_feature_extractor.extract_minutiae_features(img, spuriousMinutiaeThresh=10, invertImage=False, showResult=True, saveResult=True)`

you will get the minutiae in the variables `FeaturesTerminations` and `FeaturesBifurcations` as a list.
you will then be able to tabularize the values from there.
