### ISSUE TITLE
How can i pass an image url in the function ?

### ISSUE THREAD

**Issue by nguThapelo** [Utkarsh-Deshmukh/Fingerprint-Feature-Extraction#16]
How can i pass an image base64 url in the function ?, i tried reading it with imread but the function is rejecting it as an argument

**Comment by Utkarsh-Deshmukh** [comment]
the imread function expects the image as a standalone file on your filesystem. you may be able to use imdecode to get the image data out of the base64 encoded image, but not sure.

**Comment by nguThapelo** [comment]
Alright, Thank you.
