### ISSUE TITLE
how to save extracted features into .iso

### ISSUE THREAD

**Issue by amiroft** [Utkarsh-Deshmukh/Fingerprint-Feature-Extraction#17]
Hi
thanks for your work
I was wondering how we can integrate this code with openafis([here](https://github.com/neilharan/openafis) for high performance finger print matching. it takes .iso file of fingerprint and returns match one from database. 
by .iso it means ISO/IEC 19794-2:2005 which is standard for saving fingerprint features in file (https://www.iso.org/standard/38746.html)
Does any one has any idea how to save features extracted here to iso file?

**Comment by Utkarsh-Deshmukh** [comment]
i guess you will have to write a custom parser which parses the minutiae features and stores them in the ISO file. Not sure about the implementation. maybe this repo might be useful:
https://github.com/biometric-technologies/biometric-converter

**Comment by sifislaz** [comment]
You can also check out the [FingerprintIO](https://fingerprintio.machinezoo.com/) Java library in combination with [SourceAFIS](https://sourceafis.machinezoo.com/) in order to handle ISO templates
