### ISSUE TITLE
Minutiae orientation

### ISSUE THREAD

**Issue by Nazaninpdk** [Utkarsh-Deshmukh/Fingerprint-Feature-Extraction#2]
How can minutiae orientations be calculated in your code? According your code, i can just find type and location of minutiae

**Comment by Utkarsh-Deshmukh** [comment]
Thank you for letting me know that. I will start working on it today. I plan to finish it soon.

**Comment by Utkarsh-Deshmukh** [comment]
I have merged the code to get the minutiae features along with their orientations.

**Comment by Nazaninpdk** [comment]
Thank you so much. It was really important for me

**Comment by Nazaninpdk** [comment]
I have one more question. bifurcations have 3 angles. Which one is the correct angle according to this image?

![Image_004](https://user-images.githubusercontent.com/54844344/85926831-5272c280-b8b7-11ea-8de7-575d207580af.jpg)

**Comment by Utkarsh-Deshmukh** [comment]
Presently for the Bifurcations, I am reporting all the three angles. if you need to use just one, you can find the major angle (which would be the max(a-b, b-c, c-a)). These are the basic minutiae features. You can also use all the three angles for the bifurcation case. How to use these angles depends on what kind of matching algorithm you decide to use

**Comment by Nazaninpdk** [comment]
Many Thanks.
