### ISSUE TITLE
minutiae matching

### ISSUE THREAD

**Issue by Nazaninpdk** [Utkarsh-Deshmukh/Fingerprint-Feature-Extraction#4]
I have one more question. if we want to match minutiaes in two fingerprints, how can we align and match them? i have read fingerprint handbook but i couldnt understand

**Comment by Utkarsh-Deshmukh** [comment]
check these papers:
http://biometrics.cse.msu.edu/Publications/Fingerprint/JainHongBolle_OnlineFPVerification_PAMI.pdf

You need to find point correspondences. Here are papers which may be useful:
- http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.105.4660&rep=rep1&type=pdf
- http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.36.5382&rep=rep1&type=pdf
