### ISSUE TITLE
Algorithm used

### ISSUE THREAD

**Issue by JulienMar** [Utkarsh-Deshmukh/Fingerprint-Feature-Extraction#7]
Hi,

I was wondering which kind of algorithm the minutiae extraction was based on.

Thanks!

**Comment by Utkarsh-Deshmukh** [comment]
please refer to this document:
https://www.peterkovesi.com/studentprojects/raymondthai/RaymondThai.pdf

the section 3.1.1 - "Minutiae extraction" explains the algorithm

**Comment by JulienMar** [comment]
Thank you! This is what I needed!
