### ISSUE TITLE
match features using BFMatcher

### ISSUE THREAD

**Issue by m3di** [Utkarsh-Deshmukh/Fingerprint-Feature-Extraction#8]
Hi, I'm kind of new in this field. i will appreciate if you give me some advise.
I want to check whether two fingerprint will match or not.
First i enhanced my fingerprint pictures then i extracted FeaturesTerminations, FeaturesBifurcations of both.
Next i have to use some cv2 matcher like brute-force descriptor matcher to match FeaturesBifurcations. as i understanded i need to define a custom distance metric. 
What would be a good distance metric for FeaturesBifurcations object?

**Comment by Utkarsh-Deshmukh** [comment]
check this issue:
https://github.com/Utkarsh-Deshmukh/Fingerprint-Feature-Extraction/issues/4

Best Regards
