### ISSUE TITLE
Can you implement Minutiae Matching?

### ISSUE THREAD

**Issue by Adeel-Intizar** [Utkarsh-Deshmukh/Fingerprint-Feature-Extraction#9]
Hello, thank you for your great work
Can you provide implementation of Minutiae matching for these extracted features ?

**Comment by Utkarsh-Deshmukh** [comment]
Hi @Adeel-Intizar .
I have not implemented an actual matcher yet. Here are some resources which you can use to get it running:
check these papers:
http://biometrics.cse.msu.edu/Publications/Fingerprint/JainHongBolle_OnlineFPVerification_PAMI.pdf

You need to find point correspondences. Here are papers which may be useful:

http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.105.4660&rep=rep1&type=pdf
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.36.5382&rep=rep1&type=pdf
